/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-tint": "#d0bcff",
        "background": "#121315",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#d0bcff",
        "on-surface": "#e3e2e3",
        "on-secondary": "#2f3300",
        "on-primary-fixed": "#23005c",
        "primary": "#d0bcff",
        "surface-dim": "#121315",
        "on-background": "#e3e2e3",
        "inverse-on-surface": "#303032",
        "surface-container-low": "#1b1c1d",
        "surface-container-high": "#292a2b",
        "on-surface-variant": "#cbc3d7",
        "outline": "#958ea0",
        "on-secondary-container": "#5d6400",
        "error-container": "#93000a",
        "tertiary-container": "#f55e5d",
        "tertiary-fixed": "#ffdad7",
        "surface-container-lowest": "#0d0e0f",
        "on-tertiary": "#68000e",
        "surface-container": "#1f2021",
        "on-primary": "#3c0091",
        "outline-variant": "#494454",
        "secondary-fixed-dim": "#c3d000",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#dfed1a",
        "on-secondary-fixed-variant": "#454a00",
        "tertiary-fixed-dim": "#ffb3af",
        "on-tertiary-fixed-variant": "#8e101c",
        "tertiary": "#ffb3af",
        "on-primary-fixed-variant": "#5516be",
        "surface-container-highest": "#343536",
        "primary-fixed": "#e9ddff",
        "inverse-primary": "#6d3bd7",
        "secondary-container": "#d7e404",
        "secondary": "#f5ff7d",
        "on-tertiary-fixed": "#410005",
        "primary-container": "#a078ff",
        "on-primary-container": "#340080",
        "surface": "#121315",
        "on-error": "#690005",
        "inverse-surface": "#e3e2e3",
        "surface-bright": "#38393a",
        "on-secondary-fixed": "#1b1d00",
        "on-tertiary-container": "#5c000b",
        "surface-variant": "#343536",
        "border": "var(--border)",
        "input": "var(--input)",
        "ring": "var(--ring)",
        "foreground": "var(--foreground)",
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        headline: ["Inter", 'sans-serif'],
        body: ["Inter", 'sans-serif'],
        label: ["Space Grotesk", 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      }
    },
  },
  plugins: [],
}
